method: ISCNet_WEAK
resume: False
finetune: True
weight: ["out/shapenet/2021-12-07T20:49:50.427233/model_best.pth"]
save_path: datasets/ShapeNetv2_data/encodings
seed: 1
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 8
data:
  dataset: shapenet
  split: datasets/splits/shapenet/
  num_point: 2
  num_target: 512
  num_samples: 32
  vote_factor: 1
  num_classes: 8
  cluster_sampling: vote_fps
  ap_iou_thresh: 0.25
  no_height: False
  use_color_detection: False
  use_color_completion: False
  shapenet_path: datasets/ShapeNetv2_data
  points_unpackbits: True
  points_subsample: [1024, 1024]
  hidden_dim: 512
  c_dim: 512
  z_dim: 32
  threshold: 0.5
  completion_limit_in_train: 1
  use_cls_for_completion: False
  skip_propagate: True
model:
  completion:
    method: ONet
    loss: ONet_Prior_Loss # reconstruction loss
    weight: 0.005
  class_encode:
    method: ClassEncoder
    loss: PriorClassificationLoss
    weight: 0.3
gen_encode:
  phase: 'prior'
  batch_size: 64
# redundunt
val:
  phase: 'prior'
  batch_size: 64
log:
  vis_path: visualization
  save_results: True
  vis_step: 500
  print_step: 10
  path: out/iscnet