method: ISCNet_WEAK
resume: False
finetune: True
weight: ["out/shapenet/2021-12-08T20:18:49.786841/model_best.pth"]
seed: 1
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 8
data:
  dataset: shapenet
  split: datasets/splits/shapenet/
  num_point: 2
  num_target: 256
  vote_factor: 1
  num_classes: 8
  cluster_sampling: vote_fps
  ap_iou_thresh: 0.25
  no_height: False
  use_color_detection: False
  use_color_completion: False
  shapenet_path: datasets/ShapeNetv2_data
  points_unpackbits: True
  points_subsample: [1024, 1024]
  hidden_dim: 512
  c_dim: 512
  z_dim: 32
  threshold: 0.5
  completion_limit_in_train: 1
  use_cls_for_completion: False
  skip_propagate: True
model:
  completion:
    method: ONet
    loss: ONet_Prior_Loss # reconstruction loss
    weight: 0.005
  class_encode:
    method: ClassEncoder
    loss: PriorClassificationLoss
    weight: 0.3
optimizer:
  method: Adam
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0
scheduler:
  patience: 20
  factor: 0.1
  threshold: 0.01
bnscheduler:
  bn_decay_step: 20
  bn_decay_rate: 0.5
  bn_momentum_init: 0.5
  bn_momentum_max: 0.001
train:
  epochs: 240
  phase: 'prior'
  freeze: []
  batch_size: 128
val:
  phase: 'prior'
  batch_size: 128
generation:
  generate_mesh: True
  resolution_0: 32
  upsampling_steps: 0
  use_sampling: False
  refinement_step: 0
  simplify_nfaces: Null
  dump_threshold: 0.5
  dump_results: True
demo:
  phase: 'prior'
log:
  vis_path: visualization
  save_results: True
  vis_step: 500
  print_step: 10
  path: out/iscnet
